### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Baikele** [IllTamer/infinitebot3#13]
群消息事件无法撤回
```yml
[07:16:00] [bot-thread-1/WARN]: java.lang.reflect.InvocationTargetException
[07:16:00] [bot-thread-1/WARN]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:16:00] [bot-thread-1/WARN]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:16:00] [bot-thread-1/WARN]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:16:00] [bot-thread-1/WARN]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[07:16:00] [bot-thread-1/WARN]:         at com.illtamer.infinite.bot.minecraft.api.EventExecutor$Dispatcher.run(EventExecutor.java:128)
[07:16:00] [bot-thread-1/WARN]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[07:16:00] [bot-thread-1/WARN]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[07:16:00] [bot-thread-1/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[07:16:00] [bot-thread-1/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[07:16:00] [bot-thread-1/WARN]:         at java.base/java.lang.Thread.run(Thread.java:834)
[07:16:00] [bot-thread-1/WARN]: Caused by: com.illtamer.infinite.bot.api.exception.APIInvokeException: RECALL_API_ERROR
[07:16:00] [bot-thread-1/WARN]:         at com.illtamer.infinite.bot.api.handler.APIHandler.request(APIHandler.java:34)
[07:16:00] [bot-thread-1/WARN]:         at com.illtamer.infinite.bot.api.handler.OpenAPIHandling.deleteMessage(OpenAPIHandling.java:24)
[07:16:00] [bot-thread-1/WARN]:         at com.illtamer.infinite.bot.api.event.message.GroupMessageEvent.recall(GroupMessageEvent.java:72)
[07:16:00] [bot-thread-1/WARN]:         at com.illtamer.infinite.bot.expansion.basic.listener.KeyWordsListener.onShowPlayers(KeyWordsListener.java:176)
[07:16:00] [bot-thread-1/WARN]:         ... 10 more
```

320版本，输入ib3 reload 会报错
```yml
[07:17:59] [Server thread/WARN]: Unexpected exception while parsing console command "ib3 reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'ib3' in plugin InfiniteBot3 v3.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:680) ~[forge:1.16.5-1d8d6313]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:666) ~[forge:1.16.5-1d8d6313]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:365) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:337) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/illtamer/infinite/bot/minecraft/start/bungee/BungeeBootstrap
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.loadConfigurations(BotConfiguration.java:79) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.reload(BotConfiguration.java:108) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.handler.CommandHelper.onCommand(CommandHelper.java:52) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.BukkitCommandListener.onCommand(BukkitCommandListener.java:17) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.illtamer.infinite.bot.minecraft.start.bungee.BungeeBootstrap
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:261) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.loadConfigurations(BotConfiguration.java:79) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.reload(BotConfiguration.java:108) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.handler.CommandHelper.onCommand(CommandHelper.java:52) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.BukkitCommandListener.onCommand(BukkitCommandListener.java:17) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: com/illtamer/infinite/bot/minecraft/configuration/EmbedRedisStarter
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.loadConfigurations(BotConfiguration.java:79) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.reload(BotConfiguration.java:108) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.handler.CommandHelper.onCommand(CommandHelper.java:52) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.BukkitCommandListener.onCommand(BukkitCommandListener.java:17) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.illtamer.infinite.bot.minecraft.configuration.EmbedRedisStarter
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:261) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.loadConfigurations(BotConfiguration.java:79) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.reload(BotConfiguration.java:108) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.handler.CommandHelper.onCommand(CommandHelper.java:52) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.BukkitCommandListener.onCommand(BukkitCommandListener.java:17) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.loadConfigurations(BotConfiguration.java:79) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.reload(BotConfiguration.java:108) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.handler.CommandHelper.onCommand(CommandHelper.java:52) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.BukkitCommandListener.onCommand(BukkitCommandListener.java:17) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.plugin.Plugin
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:175) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.loadConfigurations(BotConfiguration.java:79) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.reload(BotConfiguration.java:108) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.handler.CommandHelper.onCommand(CommandHelper.java:52) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.BukkitCommandListener.onCommand(BukkitCommandListener.java:17) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.plugin.Plugin
        at java.lang.ClassLoader.findClass(ClassLoader.java:718) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:173) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.loadConfigurations(BotConfiguration.java:79) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.reload(BotConfiguration.java:108) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.handler.CommandHelper.onCommand(CommandHelper.java:52) ~[?:?]
        at com.illtamer.infinite.bot.minecraft.listener.BukkitCommandListener.onCommand(BukkitCommandListener.java:17) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        ... 9 more
        Suppressed: java.lang.ClassNotFoundException
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.1.3.jar:?]
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:173) ~[forge:?]
                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
                at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
                at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
                at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
                at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
                at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
                at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
                at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.loadConfigurations(BotConfiguration.java:79) ~[?:?]
                at com.illtamer.infinite.bot.minecraft.configuration.config.BotConfiguration.reload(BotConfiguration.java:108) ~[?:?]
                at com.illtamer.infinite.bot.minecraft.listener.handler.CommandHelper.onCommand(CommandHelper.java:52) ~[?:?]
                at com.illtamer.infinite.bot.minecraft.listener.BukkitCommandListener.onCommand(BukkitCommandListener.java:17) ~[?:?]
                at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
                at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[forge:?]
                at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:680) ~[forge:1.16.5-1d8d6313]
                at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:666) ~[forge:1.16.5-1d8d6313]
                at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:365) ~[?:?]
                at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:337) ~[?:?]
                at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
                at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
                at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
                at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Baikele** [comment]
if(event.getRawMessage().equals("测试消息")){
            event.recall();
        }

撤回群消息的代码

**Comment by Baikele** [comment]
第一个的问题，是因为我是群主发的消息，不能呗撤回

**Comment by IllTamer** [comment]
> 第一个的问题，是因为我是群主发的消息，不能呗撤回

管理员无权撤回群主所发消息，故撤回失败接口报错，属正常现象，需调用者自行设置异常逻辑

**Comment by IllTamer** [comment]
另3.2.0版本bungee模式仍在调试中，请在配置文件中关闭bungee模式（3.2.0本体配置文件需手动删除更新），后续测试完成后将会更新配置教程，具体更新将于本月内完成。
